spring.application.name=rental-house-microservice

# Server Port configuration for 1st service
server.port=8082

# Database Configuration (Database Name: rental_house)
spring.datasource.url=jdbc:mysql://localhost:3306/rental_house
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
